<?php
/**
 * ConsultingDateAdd
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ConsultingDateAdd model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class ConsultingDateAdd 
{
        /**
     * id of consulting menu item
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * title of consulting menu item (&#x3D; menuname)
     *
     * @var string|null
     * @SerializedName("title")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $title;

    /**
     * format DD.MM.YYYY
     *
     * @var string|null
     * @SerializedName("date")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $date;

    /**
     * format HH\\:II
     *
     * @var string|null
     * @SerializedName("time")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $time;

    /**
     * location selection
     *
     * @var string|null
     * @SerializedName("location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $location;

    /**
     * consultant name
     *
     * @var string|null
     * @SerializedName("consultant")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $consultant;

    /**
     * free notice
     *
     * @var string|null
     * @SerializedName("notice")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $notice;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->title = isset($data['title']) ? $data['title'] : null;
        $this->date = isset($data['date']) ? $data['date'] : null;
        $this->time = isset($data['time']) ? $data['time'] : null;
        $this->location = isset($data['location']) ? $data['location'] : null;
        $this->consultant = isset($data['consultant']) ? $data['consultant'] : null;
        $this->notice = isset($data['notice']) ? $data['notice'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id  id of consulting menu item
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets title.
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Sets title.
     *
     * @param string|null $title  title of consulting menu item (= menuname)
     *
     * @return $this
     */
    public function setTitle($title = null)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Gets date.
     *
     * @return string|null
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Sets date.
     *
     * @param string|null $date  format DD.MM.YYYY
     *
     * @return $this
     */
    public function setDate($date = null)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Gets time.
     *
     * @return string|null
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Sets time.
     *
     * @param string|null $time  format HH\\:II
     *
     * @return $this
     */
    public function setTime($time = null)
    {
        $this->time = $time;

        return $this;
    }

    /**
     * Gets location.
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Sets location.
     *
     * @param string|null $location  location selection
     *
     * @return $this
     */
    public function setLocation($location = null)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Gets consultant.
     *
     * @return string|null
     */
    public function getConsultant()
    {
        return $this->consultant;
    }

    /**
     * Sets consultant.
     *
     * @param string|null $consultant  consultant name
     *
     * @return $this
     */
    public function setConsultant($consultant = null)
    {
        $this->consultant = $consultant;

        return $this;
    }

    /**
     * Gets notice.
     *
     * @return string|null
     */
    public function getNotice()
    {
        return $this->notice;
    }

    /**
     * Sets notice.
     *
     * @param string|null $notice  free notice
     *
     * @return $this
     */
    public function setNotice($notice = null)
    {
        $this->notice = $notice;

        return $this;
    }
}


