<?php
/**
 * ConsultingDateGetArticle
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ConsultingDateGetArticle model.
 *
 * article structure
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class ConsultingDateGetArticle 
{
        /**
     * should be \&quot;info-card\&quot; always
     *
     * @var string|null
     * @SerializedName("type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * id of article
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var BSC\Model\ConsultingDateGetArticleValue|null
     * @SerializedName("value")
     * @Assert\Type("BSC\Model\ConsultingDateGetArticleValue")
     * @Type("BSC\Model\ConsultingDateGetArticleValue")
     */
    protected $value;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->value = isset($data['value']) ? $data['value'] : null;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type  should be \"info-card\" always
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id  id of article
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets value.
     *
     * @return BSC\Model\ConsultingDateGetArticleValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Sets value.
     *
     * @param BSC\Model\ConsultingDateGetArticleValue|null $value
     *
     * @return $this
     */
    public function setValue(ConsultingDateGetArticleValue $value = null)
    {
        $this->value = $value;

        return $this;
    }
}


