<?php
/**
 * ConsultingDateGetArticleValue
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ConsultingDateGetArticleValue model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class ConsultingDateGetArticleValue 
{
        /**
     * @var BSC\Model\ConsultingDateGetArticleValueMenuname|null
     * @SerializedName("menuname")
     * @Assert\Type("BSC\Model\ConsultingDateGetArticleValueMenuname")
     * @Type("BSC\Model\ConsultingDateGetArticleValueMenuname")
     */
    protected $menuname;

    /**
     * @var BSC\Model\ConsultingDateGetArticleValueTitle|null
     * @SerializedName("title")
     * @Assert\Type("BSC\Model\ConsultingDateGetArticleValueTitle")
     * @Type("BSC\Model\ConsultingDateGetArticleValueTitle")
     */
    protected $title;

    /**
     * @var BSC\Model\ConsultingDateGetArticleValueDesc|null
     * @SerializedName("desc")
     * @Assert\Type("BSC\Model\ConsultingDateGetArticleValueDesc")
     * @Type("BSC\Model\ConsultingDateGetArticleValueDesc")
     */
    protected $desc;

    /**
     * pairs of label, value
     *
     * @var BSC\Model\ConsultingOverviewFacts[]|null
     * @SerializedName("facts")
     * @Assert\All({
     *   @Assert\Type("BSC\Model\ConsultingOverviewFacts")
     * })
     * @Type("array<BSC\Model\ConsultingOverviewFacts>")
     */
    protected $facts;

    /**
     * @var BSC\Model\ConsultingDateGetArticleValueOverlay|null
     * @SerializedName("overlay")
     * @Assert\Type("BSC\Model\ConsultingDateGetArticleValueOverlay")
     * @Type("BSC\Model\ConsultingDateGetArticleValueOverlay")
     */
    protected $overlay;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->menuname = isset($data['menuname']) ? $data['menuname'] : null;
        $this->title = isset($data['title']) ? $data['title'] : null;
        $this->desc = isset($data['desc']) ? $data['desc'] : null;
        $this->facts = isset($data['facts']) ? $data['facts'] : null;
        $this->overlay = isset($data['overlay']) ? $data['overlay'] : null;
    }

    /**
     * Gets menuname.
     *
     * @return BSC\Model\ConsultingDateGetArticleValueMenuname|null
     */
    public function getMenuname()
    {
        return $this->menuname;
    }

    /**
     * Sets menuname.
     *
     * @param BSC\Model\ConsultingDateGetArticleValueMenuname|null $menuname
     *
     * @return $this
     */
    public function setMenuname(ConsultingDateGetArticleValueMenuname $menuname = null)
    {
        $this->menuname = $menuname;

        return $this;
    }

    /**
     * Gets title.
     *
     * @return BSC\Model\ConsultingDateGetArticleValueTitle|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Sets title.
     *
     * @param BSC\Model\ConsultingDateGetArticleValueTitle|null $title
     *
     * @return $this
     */
    public function setTitle(ConsultingDateGetArticleValueTitle $title = null)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Gets desc.
     *
     * @return BSC\Model\ConsultingDateGetArticleValueDesc|null
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Sets desc.
     *
     * @param BSC\Model\ConsultingDateGetArticleValueDesc|null $desc
     *
     * @return $this
     */
    public function setDesc(ConsultingDateGetArticleValueDesc $desc = null)
    {
        $this->desc = $desc;

        return $this;
    }

    /**
     * Gets facts.
     *
     * @return BSC\Model\ConsultingOverviewFacts[]|null
     */
    public function getFacts()
    {
        return $this->facts;
    }

    /**
     * Sets facts.
     *
     * @param BSC\Model\ConsultingOverviewFacts[]|null $facts  pairs of label, value
     *
     * @return $this
     */
    public function setFacts(ConsultingOverviewFacts $facts = null)
    {
        $this->facts = $facts;

        return $this;
    }

    /**
     * Gets overlay.
     *
     * @return BSC\Model\ConsultingDateGetArticleValueOverlay|null
     */
    public function getOverlay()
    {
        return $this->overlay;
    }

    /**
     * Sets overlay.
     *
     * @param BSC\Model\ConsultingDateGetArticleValueOverlay|null $overlay
     *
     * @return $this
     */
    public function setOverlay(ConsultingDateGetArticleValueOverlay $overlay = null)
    {
        $this->overlay = $overlay;

        return $this;
    }
}


