<?php
/**
 * Error
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Error model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class Error 
{
        /**
     * @var string|null
     * @SerializedName("error")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $error;

    /**
     * @var string|null
     * @SerializedName("error_description")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $errorDescription;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->error = isset($data['error']) ? $data['error'] : null;
        $this->errorDescription = isset($data['errorDescription']) ? $data['errorDescription'] : null;
    }

    /**
     * Gets error.
     *
     * @return string|null
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Sets error.
     *
     * @param string|null $error
     *
     * @return $this
     */
    public function setError($error = null)
    {
        $this->error = $error;

        return $this;
    }

    /**
     * Gets errorDescription.
     *
     * @return string|null
     */
    public function getErrorDescription()
    {
        return $this->errorDescription;
    }

    /**
     * Sets errorDescription.
     *
     * @param string|null $errorDescription
     *
     * @return $this
     */
    public function setErrorDescription($errorDescription = null)
    {
        $this->errorDescription = $errorDescription;

        return $this;
    }
}


