<?php
/**
 * Member
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Member model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class Member 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("education_id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $educationId;

    /**
     * @var string|null
     * @SerializedName("firstname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $firstname;

    /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var string|null
     * @SerializedName("email")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $email;

    /**
     * @var string|null
     * @SerializedName("gender")
     * @Assert\Choice({ "male", "female", "none" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $gender;

    /**
     * @var string|null
     * @SerializedName("birthday")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $birthday;

    /**
     * @var string|null
     * @SerializedName("zipcode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $zipcode;

    /**
     * @var string|null
     * @SerializedName("place")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $place;

    /**
     * @var string|null
     * @SerializedName("state")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $state;

    /**
     * @var string|null
     * @SerializedName("country")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $country;

    /**
     * @var string|null
     * @SerializedName("language")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $language;

    /**
     * @var string|null
     * @SerializedName("last_milestone_action")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $lastMilestoneAction;

    /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * @var int|null
     * @SerializedName("login_tries")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $loginTries;

    /**
     * @var bool|null
     * @SerializedName("termsofuse_science_accepted")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $termsofuseScienceAccepted;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->educationId = isset($data['educationId']) ? $data['educationId'] : null;
        $this->firstname = isset($data['firstname']) ? $data['firstname'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->email = isset($data['email']) ? $data['email'] : null;
        $this->gender = isset($data['gender']) ? $data['gender'] : null;
        $this->birthday = isset($data['birthday']) ? $data['birthday'] : null;
        $this->zipcode = isset($data['zipcode']) ? $data['zipcode'] : null;
        $this->place = isset($data['place']) ? $data['place'] : null;
        $this->state = isset($data['state']) ? $data['state'] : null;
        $this->country = isset($data['country']) ? $data['country'] : null;
        $this->language = isset($data['language']) ? $data['language'] : null;
        $this->lastMilestoneAction = isset($data['lastMilestoneAction']) ? $data['lastMilestoneAction'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->loginTries = isset($data['loginTries']) ? $data['loginTries'] : null;
        $this->termsofuseScienceAccepted = isset($data['termsofuseScienceAccepted']) ? $data['termsofuseScienceAccepted'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets educationId.
     *
     * @return string|null
     */
    public function getEducationId()
    {
        return $this->educationId;
    }

    /**
     * Sets educationId.
     *
     * @param string|null $educationId
     *
     * @return $this
     */
    public function setEducationId($educationId = null)
    {
        $this->educationId = $educationId;

        return $this;
    }

    /**
     * Gets firstname.
     *
     * @return string|null
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Sets firstname.
     *
     * @param string|null $firstname
     *
     * @return $this
     */
    public function setFirstname($firstname = null)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email
     *
     * @return $this
     */
    public function setEmail($email = null)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets gender.
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Sets gender.
     *
     * @param string|null $gender
     *
     * @return $this
     */
    public function setGender($gender = null)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Gets birthday.
     *
     * @return string|null
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Sets birthday.
     *
     * @param string|null $birthday
     *
     * @return $this
     */
    public function setBirthday($birthday = null)
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * Gets zipcode.
     *
     * @return string|null
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Sets zipcode.
     *
     * @param string|null $zipcode
     *
     * @return $this
     */
    public function setZipcode($zipcode = null)
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * Gets place.
     *
     * @return string|null
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Sets place.
     *
     * @param string|null $place
     *
     * @return $this
     */
    public function setPlace($place = null)
    {
        $this->place = $place;

        return $this;
    }

    /**
     * Gets state.
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Sets state.
     *
     * @param string|null $state
     *
     * @return $this
     */
    public function setState($state = null)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Gets country.
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Sets country.
     *
     * @param string|null $country
     *
     * @return $this
     */
    public function setCountry($country = null)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Gets language.
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Sets language.
     *
     * @param string|null $language
     *
     * @return $this
     */
    public function setLanguage($language = null)
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Gets lastMilestoneAction.
     *
     * @return string|null
     */
    public function getLastMilestoneAction()
    {
        return $this->lastMilestoneAction;
    }

    /**
     * Sets lastMilestoneAction.
     *
     * @param string|null $lastMilestoneAction
     *
     * @return $this
     */
    public function setLastMilestoneAction($lastMilestoneAction = null)
    {
        $this->lastMilestoneAction = $lastMilestoneAction;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets loginTries.
     *
     * @return int|null
     */
    public function getLoginTries()
    {
        return $this->loginTries;
    }

    /**
     * Sets loginTries.
     *
     * @param int|null $loginTries
     *
     * @return $this
     */
    public function setLoginTries($loginTries = null)
    {
        $this->loginTries = $loginTries;

        return $this;
    }

    /**
     * Gets termsofuseScienceAccepted.
     *
     * @return bool|null
     */
    public function isTermsofuseScienceAccepted()
    {
        return $this->termsofuseScienceAccepted;
    }

    /**
     * Sets termsofuseScienceAccepted.
     *
     * @param bool|null $termsofuseScienceAccepted
     *
     * @return $this
     */
    public function setTermsofuseScienceAccepted($termsofuseScienceAccepted = null)
    {
        $this->termsofuseScienceAccepted = $termsofuseScienceAccepted;

        return $this;
    }
}


