<?php
/**
 * MemberPatch
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MemberPatch model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class MemberPatch 
{
        /**
     * @var string|null
     * @SerializedName("firstname")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $firstname;

    /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var string|null
     * @SerializedName("email")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $email;

    /**
     * @var string|null
     * @SerializedName("gender")
     * @Assert\Choice({ "male", "female", "none" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $gender;

    /**
     * @var string|null
     * @SerializedName("zipcode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $zipcode;

    /**
     * @var string|null
     * @SerializedName("place")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $place;

    /**
     * @var string|null
     * @SerializedName("country")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $country;

    /**
     * @var bool|null
     * @SerializedName("termsofuse_science_accepted")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $termsofuseScienceAccepted;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->firstname = isset($data['firstname']) ? $data['firstname'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->email = isset($data['email']) ? $data['email'] : null;
        $this->gender = isset($data['gender']) ? $data['gender'] : null;
        $this->zipcode = isset($data['zipcode']) ? $data['zipcode'] : null;
        $this->place = isset($data['place']) ? $data['place'] : null;
        $this->country = isset($data['country']) ? $data['country'] : null;
        $this->termsofuseScienceAccepted = isset($data['termsofuseScienceAccepted']) ? $data['termsofuseScienceAccepted'] : null;
    }

    /**
     * Gets firstname.
     *
     * @return string|null
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Sets firstname.
     *
     * @param string|null $firstname
     *
     * @return $this
     */
    public function setFirstname($firstname = null)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email
     *
     * @return $this
     */
    public function setEmail($email = null)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets gender.
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Sets gender.
     *
     * @param string|null $gender
     *
     * @return $this
     */
    public function setGender($gender = null)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Gets zipcode.
     *
     * @return string|null
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Sets zipcode.
     *
     * @param string|null $zipcode
     *
     * @return $this
     */
    public function setZipcode($zipcode = null)
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * Gets place.
     *
     * @return string|null
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Sets place.
     *
     * @param string|null $place
     *
     * @return $this
     */
    public function setPlace($place = null)
    {
        $this->place = $place;

        return $this;
    }

    /**
     * Gets country.
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Sets country.
     *
     * @param string|null $country
     *
     * @return $this
     */
    public function setCountry($country = null)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Gets termsofuseScienceAccepted.
     *
     * @return bool|null
     */
    public function isTermsofuseScienceAccepted()
    {
        return $this->termsofuseScienceAccepted;
    }

    /**
     * Sets termsofuseScienceAccepted.
     *
     * @param bool|null $termsofuseScienceAccepted
     *
     * @return $this
     */
    public function setTermsofuseScienceAccepted($termsofuseScienceAccepted = null)
    {
        $this->termsofuseScienceAccepted = $termsofuseScienceAccepted;

        return $this;
    }
}


