<?php
/**
 * MessageGetConversation
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MessageGetConversation model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class MessageGetConversation 
{
        /**
     * id of the reply message
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var bool|null
     * @SerializedName("read")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $read;

    /**
     * @var string|null
     * @SerializedName("content")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $content;

    /**
     * @var string|null
     * @SerializedName("createdate")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $createdate;

    /**
     * unix timestamp (seconds)
     *
     * @var int|null
     * @SerializedName("createtimestamp")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $createtimestamp;

    /**
     * API (user) or BACKEND_USER (BTU)
     *
     * @var string|null
     * @SerializedName("createdby")
     * @Assert\Choice({ "API", "BACKEND_USER" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $createdby;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->read = isset($data['read']) ? $data['read'] : null;
        $this->content = isset($data['content']) ? $data['content'] : null;
        $this->createdate = isset($data['createdate']) ? $data['createdate'] : null;
        $this->createtimestamp = isset($data['createtimestamp']) ? $data['createtimestamp'] : null;
        $this->createdby = isset($data['createdby']) ? $data['createdby'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id  id of the reply message
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets read.
     *
     * @return bool|null
     */
    public function isRead()
    {
        return $this->read;
    }

    /**
     * Sets read.
     *
     * @param bool|null $read
     *
     * @return $this
     */
    public function setRead($read = null)
    {
        $this->read = $read;

        return $this;
    }

    /**
     * Gets content.
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Sets content.
     *
     * @param string|null $content
     *
     * @return $this
     */
    public function setContent($content = null)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Gets createdate.
     *
     * @return string|null
     */
    public function getCreatedate()
    {
        return $this->createdate;
    }

    /**
     * Sets createdate.
     *
     * @param string|null $createdate
     *
     * @return $this
     */
    public function setCreatedate($createdate = null)
    {
        $this->createdate = $createdate;

        return $this;
    }

    /**
     * Gets createtimestamp.
     *
     * @return int|null
     */
    public function getCreatetimestamp()
    {
        return $this->createtimestamp;
    }

    /**
     * Sets createtimestamp.
     *
     * @param int|null $createtimestamp  unix timestamp (seconds)
     *
     * @return $this
     */
    public function setCreatetimestamp($createtimestamp = null)
    {
        $this->createtimestamp = $createtimestamp;

        return $this;
    }

    /**
     * Gets createdby.
     *
     * @return string|null
     */
    public function getCreatedby()
    {
        return $this->createdby;
    }

    /**
     * Sets createdby.
     *
     * @param string|null $createdby  API (user) or BACKEND_USER (BTU)
     *
     * @return $this
     */
    public function setCreatedby($createdby = null)
    {
        $this->createdby = $createdby;

        return $this;
    }
}


