<?php
/**
 * Milestone
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Milestone model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class Milestone 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var int|null
     * @SerializedName("type")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $type;

    /**
     * @var string|null
     * @SerializedName("status_from")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $statusFrom;

    /**
     * @var string|null
     * @SerializedName("status_until")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $statusUntil;

    /**
     * @var string|null
     * @SerializedName("school_type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $schoolType;

    /**
     * @var string|null
     * @SerializedName("school_name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $schoolName;

    /**
     * @var string|null
     * @SerializedName("school_location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $schoolLocation;

    /**
     * @var int|null
     * @SerializedName("school_grade")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $schoolGrade;

    /**
     * @var string|null
     * @SerializedName("school_graduation")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $schoolGraduation;

    /**
     * @var string|null
     * @SerializedName("school_after")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $schoolAfter;

    /**
     * @var string|null
     * @SerializedName("university_course")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityCourse;

    /**
     * @var string|null
     * @SerializedName("university_type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityType;

    /**
     * @var string|null
     * @SerializedName("university_name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityName;

    /**
     * @var string|null
     * @SerializedName("university_location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityLocation;

    /**
     * @var int|null
     * @SerializedName("university_semester")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $universitySemester;

    /**
     * @var string|null
     * @SerializedName("university_student_number")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityStudentNumber;

    /**
     * @var string|null
     * @SerializedName("university_educational_achievement")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityEducationalAchievement;

    /**
     * @var string|null
     * @SerializedName("university_graduation")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityGraduation;

    /**
     * @var string|null
     * @SerializedName("university_after")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $universityAfter;

    /**
     * @var string|null
     * @SerializedName("voluntary_type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $voluntaryType;

    /**
     * @var string|null
     * @SerializedName("voluntary_name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $voluntaryName;

    /**
     * @var string|null
     * @SerializedName("voluntary_location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $voluntaryLocation;

    /**
     * @var string|null
     * @SerializedName("voluntary_educational_achievement")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $voluntaryEducationalAchievement;

    /**
     * @var string|null
     * @SerializedName("voluntary_after")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $voluntaryAfter;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipType;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipName;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipLocation;

    /**
     * @var int|null
     * @SerializedName("apprenticeship_year")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $apprenticeshipYear;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_educational_achievement")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipEducationalAchievement;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_graduation")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipGraduation;

    /**
     * @var string|null
     * @SerializedName("apprenticeship_after")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $apprenticeshipAfter;

    /**
     * @var string|null
     * @SerializedName("else_name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $elseName;

    /**
     * @var string|null
     * @SerializedName("else_location")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $elseLocation;

    /**
     * @var string|null
     * @SerializedName("else_educational_achievement")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $elseEducationalAchievement;

    /**
     * @var string|null
     * @SerializedName("else_after")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $elseAfter;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->statusFrom = isset($data['statusFrom']) ? $data['statusFrom'] : null;
        $this->statusUntil = isset($data['statusUntil']) ? $data['statusUntil'] : null;
        $this->schoolType = isset($data['schoolType']) ? $data['schoolType'] : null;
        $this->schoolName = isset($data['schoolName']) ? $data['schoolName'] : null;
        $this->schoolLocation = isset($data['schoolLocation']) ? $data['schoolLocation'] : null;
        $this->schoolGrade = isset($data['schoolGrade']) ? $data['schoolGrade'] : null;
        $this->schoolGraduation = isset($data['schoolGraduation']) ? $data['schoolGraduation'] : null;
        $this->schoolAfter = isset($data['schoolAfter']) ? $data['schoolAfter'] : null;
        $this->universityCourse = isset($data['universityCourse']) ? $data['universityCourse'] : null;
        $this->universityType = isset($data['universityType']) ? $data['universityType'] : null;
        $this->universityName = isset($data['universityName']) ? $data['universityName'] : null;
        $this->universityLocation = isset($data['universityLocation']) ? $data['universityLocation'] : null;
        $this->universitySemester = isset($data['universitySemester']) ? $data['universitySemester'] : null;
        $this->universityStudentNumber = isset($data['universityStudentNumber']) ? $data['universityStudentNumber'] : null;
        $this->universityEducationalAchievement = isset($data['universityEducationalAchievement']) ? $data['universityEducationalAchievement'] : null;
        $this->universityGraduation = isset($data['universityGraduation']) ? $data['universityGraduation'] : null;
        $this->universityAfter = isset($data['universityAfter']) ? $data['universityAfter'] : null;
        $this->voluntaryType = isset($data['voluntaryType']) ? $data['voluntaryType'] : null;
        $this->voluntaryName = isset($data['voluntaryName']) ? $data['voluntaryName'] : null;
        $this->voluntaryLocation = isset($data['voluntaryLocation']) ? $data['voluntaryLocation'] : null;
        $this->voluntaryEducationalAchievement = isset($data['voluntaryEducationalAchievement']) ? $data['voluntaryEducationalAchievement'] : null;
        $this->voluntaryAfter = isset($data['voluntaryAfter']) ? $data['voluntaryAfter'] : null;
        $this->apprenticeshipType = isset($data['apprenticeshipType']) ? $data['apprenticeshipType'] : null;
        $this->apprenticeshipName = isset($data['apprenticeshipName']) ? $data['apprenticeshipName'] : null;
        $this->apprenticeshipLocation = isset($data['apprenticeshipLocation']) ? $data['apprenticeshipLocation'] : null;
        $this->apprenticeshipYear = isset($data['apprenticeshipYear']) ? $data['apprenticeshipYear'] : null;
        $this->apprenticeshipEducationalAchievement = isset($data['apprenticeshipEducationalAchievement']) ? $data['apprenticeshipEducationalAchievement'] : null;
        $this->apprenticeshipGraduation = isset($data['apprenticeshipGraduation']) ? $data['apprenticeshipGraduation'] : null;
        $this->apprenticeshipAfter = isset($data['apprenticeshipAfter']) ? $data['apprenticeshipAfter'] : null;
        $this->elseName = isset($data['elseName']) ? $data['elseName'] : null;
        $this->elseLocation = isset($data['elseLocation']) ? $data['elseLocation'] : null;
        $this->elseEducationalAchievement = isset($data['elseEducationalAchievement']) ? $data['elseEducationalAchievement'] : null;
        $this->elseAfter = isset($data['elseAfter']) ? $data['elseAfter'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return int|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param int|null $type
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets statusFrom.
     *
     * @return string|null
     */
    public function getStatusFrom()
    {
        return $this->statusFrom;
    }

    /**
     * Sets statusFrom.
     *
     * @param string|null $statusFrom
     *
     * @return $this
     */
    public function setStatusFrom($statusFrom = null)
    {
        $this->statusFrom = $statusFrom;

        return $this;
    }

    /**
     * Gets statusUntil.
     *
     * @return string|null
     */
    public function getStatusUntil()
    {
        return $this->statusUntil;
    }

    /**
     * Sets statusUntil.
     *
     * @param string|null $statusUntil
     *
     * @return $this
     */
    public function setStatusUntil($statusUntil = null)
    {
        $this->statusUntil = $statusUntil;

        return $this;
    }

    /**
     * Gets schoolType.
     *
     * @return string|null
     */
    public function getSchoolType()
    {
        return $this->schoolType;
    }

    /**
     * Sets schoolType.
     *
     * @param string|null $schoolType
     *
     * @return $this
     */
    public function setSchoolType($schoolType = null)
    {
        $this->schoolType = $schoolType;

        return $this;
    }

    /**
     * Gets schoolName.
     *
     * @return string|null
     */
    public function getSchoolName()
    {
        return $this->schoolName;
    }

    /**
     * Sets schoolName.
     *
     * @param string|null $schoolName
     *
     * @return $this
     */
    public function setSchoolName($schoolName = null)
    {
        $this->schoolName = $schoolName;

        return $this;
    }

    /**
     * Gets schoolLocation.
     *
     * @return string|null
     */
    public function getSchoolLocation()
    {
        return $this->schoolLocation;
    }

    /**
     * Sets schoolLocation.
     *
     * @param string|null $schoolLocation
     *
     * @return $this
     */
    public function setSchoolLocation($schoolLocation = null)
    {
        $this->schoolLocation = $schoolLocation;

        return $this;
    }

    /**
     * Gets schoolGrade.
     *
     * @return int|null
     */
    public function getSchoolGrade()
    {
        return $this->schoolGrade;
    }

    /**
     * Sets schoolGrade.
     *
     * @param int|null $schoolGrade
     *
     * @return $this
     */
    public function setSchoolGrade($schoolGrade = null)
    {
        $this->schoolGrade = $schoolGrade;

        return $this;
    }

    /**
     * Gets schoolGraduation.
     *
     * @return string|null
     */
    public function getSchoolGraduation()
    {
        return $this->schoolGraduation;
    }

    /**
     * Sets schoolGraduation.
     *
     * @param string|null $schoolGraduation
     *
     * @return $this
     */
    public function setSchoolGraduation($schoolGraduation = null)
    {
        $this->schoolGraduation = $schoolGraduation;

        return $this;
    }

    /**
     * Gets schoolAfter.
     *
     * @return string|null
     */
    public function getSchoolAfter()
    {
        return $this->schoolAfter;
    }

    /**
     * Sets schoolAfter.
     *
     * @param string|null $schoolAfter
     *
     * @return $this
     */
    public function setSchoolAfter($schoolAfter = null)
    {
        $this->schoolAfter = $schoolAfter;

        return $this;
    }

    /**
     * Gets universityCourse.
     *
     * @return string|null
     */
    public function getUniversityCourse()
    {
        return $this->universityCourse;
    }

    /**
     * Sets universityCourse.
     *
     * @param string|null $universityCourse
     *
     * @return $this
     */
    public function setUniversityCourse($universityCourse = null)
    {
        $this->universityCourse = $universityCourse;

        return $this;
    }

    /**
     * Gets universityType.
     *
     * @return string|null
     */
    public function getUniversityType()
    {
        return $this->universityType;
    }

    /**
     * Sets universityType.
     *
     * @param string|null $universityType
     *
     * @return $this
     */
    public function setUniversityType($universityType = null)
    {
        $this->universityType = $universityType;

        return $this;
    }

    /**
     * Gets universityName.
     *
     * @return string|null
     */
    public function getUniversityName()
    {
        return $this->universityName;
    }

    /**
     * Sets universityName.
     *
     * @param string|null $universityName
     *
     * @return $this
     */
    public function setUniversityName($universityName = null)
    {
        $this->universityName = $universityName;

        return $this;
    }

    /**
     * Gets universityLocation.
     *
     * @return string|null
     */
    public function getUniversityLocation()
    {
        return $this->universityLocation;
    }

    /**
     * Sets universityLocation.
     *
     * @param string|null $universityLocation
     *
     * @return $this
     */
    public function setUniversityLocation($universityLocation = null)
    {
        $this->universityLocation = $universityLocation;

        return $this;
    }

    /**
     * Gets universitySemester.
     *
     * @return int|null
     */
    public function getUniversitySemester()
    {
        return $this->universitySemester;
    }

    /**
     * Sets universitySemester.
     *
     * @param int|null $universitySemester
     *
     * @return $this
     */
    public function setUniversitySemester($universitySemester = null)
    {
        $this->universitySemester = $universitySemester;

        return $this;
    }

    /**
     * Gets universityStudentNumber.
     *
     * @return string|null
     */
    public function getUniversityStudentNumber()
    {
        return $this->universityStudentNumber;
    }

    /**
     * Sets universityStudentNumber.
     *
     * @param string|null $universityStudentNumber
     *
     * @return $this
     */
    public function setUniversityStudentNumber($universityStudentNumber = null)
    {
        $this->universityStudentNumber = $universityStudentNumber;

        return $this;
    }

    /**
     * Gets universityEducationalAchievement.
     *
     * @return string|null
     */
    public function getUniversityEducationalAchievement()
    {
        return $this->universityEducationalAchievement;
    }

    /**
     * Sets universityEducationalAchievement.
     *
     * @param string|null $universityEducationalAchievement
     *
     * @return $this
     */
    public function setUniversityEducationalAchievement($universityEducationalAchievement = null)
    {
        $this->universityEducationalAchievement = $universityEducationalAchievement;

        return $this;
    }

    /**
     * Gets universityGraduation.
     *
     * @return string|null
     */
    public function getUniversityGraduation()
    {
        return $this->universityGraduation;
    }

    /**
     * Sets universityGraduation.
     *
     * @param string|null $universityGraduation
     *
     * @return $this
     */
    public function setUniversityGraduation($universityGraduation = null)
    {
        $this->universityGraduation = $universityGraduation;

        return $this;
    }

    /**
     * Gets universityAfter.
     *
     * @return string|null
     */
    public function getUniversityAfter()
    {
        return $this->universityAfter;
    }

    /**
     * Sets universityAfter.
     *
     * @param string|null $universityAfter
     *
     * @return $this
     */
    public function setUniversityAfter($universityAfter = null)
    {
        $this->universityAfter = $universityAfter;

        return $this;
    }

    /**
     * Gets voluntaryType.
     *
     * @return string|null
     */
    public function getVoluntaryType()
    {
        return $this->voluntaryType;
    }

    /**
     * Sets voluntaryType.
     *
     * @param string|null $voluntaryType
     *
     * @return $this
     */
    public function setVoluntaryType($voluntaryType = null)
    {
        $this->voluntaryType = $voluntaryType;

        return $this;
    }

    /**
     * Gets voluntaryName.
     *
     * @return string|null
     */
    public function getVoluntaryName()
    {
        return $this->voluntaryName;
    }

    /**
     * Sets voluntaryName.
     *
     * @param string|null $voluntaryName
     *
     * @return $this
     */
    public function setVoluntaryName($voluntaryName = null)
    {
        $this->voluntaryName = $voluntaryName;

        return $this;
    }

    /**
     * Gets voluntaryLocation.
     *
     * @return string|null
     */
    public function getVoluntaryLocation()
    {
        return $this->voluntaryLocation;
    }

    /**
     * Sets voluntaryLocation.
     *
     * @param string|null $voluntaryLocation
     *
     * @return $this
     */
    public function setVoluntaryLocation($voluntaryLocation = null)
    {
        $this->voluntaryLocation = $voluntaryLocation;

        return $this;
    }

    /**
     * Gets voluntaryEducationalAchievement.
     *
     * @return string|null
     */
    public function getVoluntaryEducationalAchievement()
    {
        return $this->voluntaryEducationalAchievement;
    }

    /**
     * Sets voluntaryEducationalAchievement.
     *
     * @param string|null $voluntaryEducationalAchievement
     *
     * @return $this
     */
    public function setVoluntaryEducationalAchievement($voluntaryEducationalAchievement = null)
    {
        $this->voluntaryEducationalAchievement = $voluntaryEducationalAchievement;

        return $this;
    }

    /**
     * Gets voluntaryAfter.
     *
     * @return string|null
     */
    public function getVoluntaryAfter()
    {
        return $this->voluntaryAfter;
    }

    /**
     * Sets voluntaryAfter.
     *
     * @param string|null $voluntaryAfter
     *
     * @return $this
     */
    public function setVoluntaryAfter($voluntaryAfter = null)
    {
        $this->voluntaryAfter = $voluntaryAfter;

        return $this;
    }

    /**
     * Gets apprenticeshipType.
     *
     * @return string|null
     */
    public function getApprenticeshipType()
    {
        return $this->apprenticeshipType;
    }

    /**
     * Sets apprenticeshipType.
     *
     * @param string|null $apprenticeshipType
     *
     * @return $this
     */
    public function setApprenticeshipType($apprenticeshipType = null)
    {
        $this->apprenticeshipType = $apprenticeshipType;

        return $this;
    }

    /**
     * Gets apprenticeshipName.
     *
     * @return string|null
     */
    public function getApprenticeshipName()
    {
        return $this->apprenticeshipName;
    }

    /**
     * Sets apprenticeshipName.
     *
     * @param string|null $apprenticeshipName
     *
     * @return $this
     */
    public function setApprenticeshipName($apprenticeshipName = null)
    {
        $this->apprenticeshipName = $apprenticeshipName;

        return $this;
    }

    /**
     * Gets apprenticeshipLocation.
     *
     * @return string|null
     */
    public function getApprenticeshipLocation()
    {
        return $this->apprenticeshipLocation;
    }

    /**
     * Sets apprenticeshipLocation.
     *
     * @param string|null $apprenticeshipLocation
     *
     * @return $this
     */
    public function setApprenticeshipLocation($apprenticeshipLocation = null)
    {
        $this->apprenticeshipLocation = $apprenticeshipLocation;

        return $this;
    }

    /**
     * Gets apprenticeshipYear.
     *
     * @return int|null
     */
    public function getApprenticeshipYear()
    {
        return $this->apprenticeshipYear;
    }

    /**
     * Sets apprenticeshipYear.
     *
     * @param int|null $apprenticeshipYear
     *
     * @return $this
     */
    public function setApprenticeshipYear($apprenticeshipYear = null)
    {
        $this->apprenticeshipYear = $apprenticeshipYear;

        return $this;
    }

    /**
     * Gets apprenticeshipEducationalAchievement.
     *
     * @return string|null
     */
    public function getApprenticeshipEducationalAchievement()
    {
        return $this->apprenticeshipEducationalAchievement;
    }

    /**
     * Sets apprenticeshipEducationalAchievement.
     *
     * @param string|null $apprenticeshipEducationalAchievement
     *
     * @return $this
     */
    public function setApprenticeshipEducationalAchievement($apprenticeshipEducationalAchievement = null)
    {
        $this->apprenticeshipEducationalAchievement = $apprenticeshipEducationalAchievement;

        return $this;
    }

    /**
     * Gets apprenticeshipGraduation.
     *
     * @return string|null
     */
    public function getApprenticeshipGraduation()
    {
        return $this->apprenticeshipGraduation;
    }

    /**
     * Sets apprenticeshipGraduation.
     *
     * @param string|null $apprenticeshipGraduation
     *
     * @return $this
     */
    public function setApprenticeshipGraduation($apprenticeshipGraduation = null)
    {
        $this->apprenticeshipGraduation = $apprenticeshipGraduation;

        return $this;
    }

    /**
     * Gets apprenticeshipAfter.
     *
     * @return string|null
     */
    public function getApprenticeshipAfter()
    {
        return $this->apprenticeshipAfter;
    }

    /**
     * Sets apprenticeshipAfter.
     *
     * @param string|null $apprenticeshipAfter
     *
     * @return $this
     */
    public function setApprenticeshipAfter($apprenticeshipAfter = null)
    {
        $this->apprenticeshipAfter = $apprenticeshipAfter;

        return $this;
    }

    /**
     * Gets elseName.
     *
     * @return string|null
     */
    public function getElseName()
    {
        return $this->elseName;
    }

    /**
     * Sets elseName.
     *
     * @param string|null $elseName
     *
     * @return $this
     */
    public function setElseName($elseName = null)
    {
        $this->elseName = $elseName;

        return $this;
    }

    /**
     * Gets elseLocation.
     *
     * @return string|null
     */
    public function getElseLocation()
    {
        return $this->elseLocation;
    }

    /**
     * Sets elseLocation.
     *
     * @param string|null $elseLocation
     *
     * @return $this
     */
    public function setElseLocation($elseLocation = null)
    {
        $this->elseLocation = $elseLocation;

        return $this;
    }

    /**
     * Gets elseEducationalAchievement.
     *
     * @return string|null
     */
    public function getElseEducationalAchievement()
    {
        return $this->elseEducationalAchievement;
    }

    /**
     * Sets elseEducationalAchievement.
     *
     * @param string|null $elseEducationalAchievement
     *
     * @return $this
     */
    public function setElseEducationalAchievement($elseEducationalAchievement = null)
    {
        $this->elseEducationalAchievement = $elseEducationalAchievement;

        return $this;
    }

    /**
     * Gets elseAfter.
     *
     * @return string|null
     */
    public function getElseAfter()
    {
        return $this->elseAfter;
    }

    /**
     * Sets elseAfter.
     *
     * @param string|null $elseAfter
     *
     * @return $this
     */
    public function setElseAfter($elseAfter = null)
    {
        $this->elseAfter = $elseAfter;

        return $this;
    }
}


