<?php
/**
 * NotificationsUnread
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the NotificationsUnread model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class NotificationsUnread 
{
        /**
     * number of unread notifications
     *
     * @var int|null
     * @SerializedName("unread")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $unread;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->unread = isset($data['unread']) ? $data['unread'] : null;
    }

    /**
     * Gets unread.
     *
     * @return int|null
     */
    public function getUnread()
    {
        return $this->unread;
    }

    /**
     * Sets unread.
     *
     * @param int|null $unread  number of unread notifications
     *
     * @return $this
     */
    public function setUnread($unread = null)
    {
        $this->unread = $unread;

        return $this;
    }
}


