<?php
/**
 * SetResetPassword
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the SetResetPassword model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class SetResetPassword 
{
        /**
     * @var string
     * @SerializedName("email")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $email;

    /**
     * @var string
     * @SerializedName("password_reset_key")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $passwordResetKey;

    /**
     * @var string
     * @SerializedName("password")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $password;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->email = isset($data['email']) ? $data['email'] : null;
        $this->passwordResetKey = isset($data['passwordResetKey']) ? $data['passwordResetKey'] : null;
        $this->password = isset($data['password']) ? $data['password'] : null;
    }

    /**
     * Gets email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string $email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets passwordResetKey.
     *
     * @return string
     */
    public function getPasswordResetKey()
    {
        return $this->passwordResetKey;
    }

    /**
     * Sets passwordResetKey.
     *
     * @param string $passwordResetKey
     *
     * @return $this
     */
    public function setPasswordResetKey($passwordResetKey)
    {
        $this->passwordResetKey = $passwordResetKey;

        return $this;
    }

    /**
     * Gets password.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Sets password.
     *
     * @param string $password
     *
     * @return $this
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }
}


