<?php
/**
 * Success
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Success model.
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class Success 
{
        /**
     * @var bool|null
     * @SerializedName("result")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $result;

    /**
     * @var string|null
     * @SerializedName("success")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $success;

    /**
     * @var string|null
     * @SerializedName("success_description")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $successDescription;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->result = isset($data['result']) ? $data['result'] : null;
        $this->success = isset($data['success']) ? $data['success'] : null;
        $this->successDescription = isset($data['successDescription']) ? $data['successDescription'] : null;
    }

    /**
     * Gets result.
     *
     * @return bool|null
     */
    public function isResult()
    {
        return $this->result;
    }

    /**
     * Sets result.
     *
     * @param bool|null $result
     *
     * @return $this
     */
    public function setResult($result = null)
    {
        $this->result = $result;

        return $this;
    }

    /**
     * Gets success.
     *
     * @return string|null
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Sets success.
     *
     * @param string|null $success
     *
     * @return $this
     */
    public function setSuccess($success = null)
    {
        $this->success = $success;

        return $this;
    }

    /**
     * Gets successDescription.
     *
     * @return string|null
     */
    public function getSuccessDescription()
    {
        return $this->successDescription;
    }

    /**
     * Sets successDescription.
     *
     * @param string|null $successDescription
     *
     * @return $this
     */
    public function setSuccessDescription($successDescription = null)
    {
        $this->successDescription = $successDescription;

        return $this;
    }
}


