<?php
/**
 * Timesheet
 *
 * PHP version 5
 *
 * @category Class
 * @package  BSC\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BSC API
 *
 * BSC API
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BSC\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Timesheet model.
 *
 * time sheet for selected participant (empty response if there are no time sheet relevant courses in current semester)
 *
 * @package BSC\Model
 * @author  Swagger Codegen team
 */
class Timesheet 
{
        /**
     * list of events of type \&quot;obligable\&quot;
     *
     * @var BSC\Model\TimesheetObligable[]|null
     * @SerializedName("obligable")
     * @Assert\All({
     *   @Assert\Type("BSC\Model\TimesheetObligable")
     * })
     * @Type("array<BSC\Model\TimesheetObligable>")
     */
    protected $obligable;

    /**
     * list of events of type \&quot;voluntary\&quot;
     *
     * @var array[]|null
     * @SerializedName("voluntary")
     * @Assert\All({
     *   @Assert\Type("array")
     * })
     * @Type("array<array>")
     */
    protected $voluntary;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->obligable = isset($data['obligable']) ? $data['obligable'] : null;
        $this->voluntary = isset($data['voluntary']) ? $data['voluntary'] : null;
    }

    /**
     * Gets obligable.
     *
     * @return BSC\Model\TimesheetObligable[]|null
     */
    public function getObligable()
    {
        return $this->obligable;
    }

    /**
     * Sets obligable.
     *
     * @param BSC\Model\TimesheetObligable[]|null $obligable  list of events of type \"obligable\"
     *
     * @return $this
     */
    public function setObligable(TimesheetObligable $obligable = null)
    {
        $this->obligable = $obligable;

        return $this;
    }

    /**
     * Gets voluntary.
     *
     * @return array[]|null
     */
    public function getVoluntary()
    {
        return $this->voluntary;
    }

    /**
     * Sets voluntary.
     *
     * @param array[]|null $voluntary  list of events of type \"voluntary\"
     *
     * @return $this
     */
    public function setVoluntary(array $voluntary = null)
    {
        $this->voluntary = $voluntary;

        return $this;
    }
}


